"use client";

import { useEffect, useState, useRef } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "../../lib/AuthContext";
import { listenQueueToday, setStatus, skipAndReinsert, bookToken } from "../../lib/queue";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const SERVICES = [
  { name: "Hair Cut", duration: 20 },
  { name: "Shave", duration: 15 },
  { name: "Hair Colour", duration: 45 },
  { name: "Facial", duration: 30 },
  { name: "Hair Wash", duration: 15 },
];

export default function AdminPage() {
  const { user, role, loading, logout } = useAuth();
  const router = useRouter();
  const [queue, setQueue] = useState([]);
  const [busyId, setBusyId] = useState(null);
  const [searchTerm, setSearchTerm] = useState("");

  const [manualName, setManualName] = useState("");
  const [manualPhone, setManualPhone] = useState("");
  const [manualService, setManualService] = useState(SERVICES[0].name);
  const [manualLoading, setManualLoading] = useState(false);
  const [manualError, setManualError] = useState("");

  const prevQueueLength = useRef(0);

  useEffect(() => {
    if (loading) return;
    if (!user || (role !== "admin" && role !== "super-admin")) {
      router.replace("/login");
    }
  }, [user, role, loading, router]);

  useEffect(() => {
    const unsub = listenQueueToday((data) => {
      if (data.length > prevQueueLength.current && prevQueueLength.current !== 0) {
        playNotificationSound();
      }
      prevQueueLength.current = data.length;
      setQueue(data);
    });
    return () => unsub();
  }, []);

  const playNotificationSound = () => {
    try {
      const audio = new Audio("/sounds/notification.mp3");
      audio.play().catch(() => {});
    } catch (e) {
      console.log("Audio play error", e);
    }
  };

  const exportToPDF = () => {
    if (!queue.length) return;

    const doc = new jsPDF();
    const todayStr = new Date().toLocaleDateString();

    doc.setFontSize(18);
    doc.setTextColor(212, 175, 55);
    doc.text("Salon Queue Management - Daily Report", 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Date: ${todayStr}`, 14, 27);
    doc.text(`Generated By: ${user?.displayName || user?.email || "Admin"}`, 14, 32);

    const doneCount = queue.filter((t) => t.status === "done").length;
    const waitingCount = queue.filter((t) => t.status === "waiting").length;
    const servingCount = queue.filter((t) => t.status === "serving").length;

    doc.setFontSize(11);
    doc.setTextColor(40);
    doc.text(`Total Bookings: ${queue.length} | Completed: ${doneCount} | Waiting: ${waitingCount} | Serving: ${servingCount}`, 14, 42);

    const tableRows = queue.map((t) => [
      `#${t.tokenNumber}`,
      t.customerName,
      t.phone || "N/A",
      t.service,
      t.status === "done" ? "COMPLETED" : t.status.toUpperCase(),
    ]);

    autoTable(doc, {
      startY: 48,
      head: [["Token #", "Customer Name", "Phone", "Service", "Status"]],
      body: tableRows,
      headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255] },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      styles: { fontSize: 9, cellPadding: 3 },
    });

    doc.save(`salon_queue_report_${new Date().toISOString().slice(0, 10)}.pdf`);
  };

  if (loading || !user) {
    return (
      <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", backgroundColor: "#0f172a", color: "#f8fafc", padding: "16px" }}>
        <p style={{ fontSize: "16px", textAlign: "center" }}>Loading Management Dashboard...</p>
      </div>
    );
  }

  const waiting = queue.filter((t) => t.status === "waiting");
  const serving = queue.find((t) => t.status === "serving");
  const skippedTokens = queue.filter((t) => t.status === "skipped");
  const doneTokens = queue.filter((t) => t.status === "done");

  const totalToday = queue.length;
  const completedToday = doneTokens.length;
  const remainingToday = waiting.length + (serving ? 1 : 0);

  const filteredWaiting = waiting.filter(
    (t) =>
      t.customerName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      t.tokenNumber.toString().includes(searchTerm)
  );

  const serviceStats = SERVICES.map((svc) => {
    const count = queue.filter((t) => t.service === svc.name).length;
    return { service: svc.name, count };
  });

  const calculateWaitTime = (index) => {
    let totalMinutes = 0;
    for (let i = 0; i < index; i++) {
      const match = SERVICES.find((s) => s.name === waiting[i].service);
      totalMinutes += match ? match.duration : 20;
    }
    return totalMinutes;
  };

  const renderAvatar = (name, photoURL, size = 42) => {
    if (photoURL) {
      return (
        <img
          src={photoURL}
          alt={name}
          style={{ width: size, height: size, borderRadius: "50%", objectFit: "cover", border: "2px solid #d4af37", flexShrink: 0 }}
        />
      );
    }
    const initial = name ? name.charAt(0).toUpperCase() : "?";
    return (
      <div
        style={{
          width: size,
          height: size,
          borderRadius: "50%",
          backgroundColor: "#334155",
          color: "#fff",
          display: "flex",
          alignItems: "center",
          justify: "center",
          fontWeight: "700",
          fontSize: size * 0.4,
          border: "2px solid #d4af37",
          flexShrink: 0,
        }}
      >
        {initial}
      </div>
    );
  };

  async function handleServeNext() {
    const next = waiting[0];
    if (!next) return;
    setBusyId(next.id);
    await setStatus(next.id, "serving");
    setBusyId(null);
  }

  async function handleDone(token) {
    setBusyId(token.id);
    await setStatus(token.id, "done");
    setBusyId(null);
  }

  async function handleSkip(token) {
    setBusyId(token.id);
    await setStatus(token.id, "skipped");
    setBusyId(null);
  }

  async function handleCancel(token) {
    if (confirm(`Are you sure you want to cancel token #${token.tokenNumber}?`)) {
      setBusyId(token.id);
      await setStatus(token.id, "cancelled");
      setBusyId(null);
    }
  }

  async function handleReinsert(token) {
    setBusyId(token.id);
    const currentOrdered = queue.filter((t) => t.status === "waiting" || t.status === "serving");
    await skipAndReinsert(token.id, currentOrdered.length ? currentOrdered : queue);
    setBusyId(null);
  }

  async function handleManualBooking(e) {
    e.preventDefault();
    setManualError("");
    if (!manualName.trim()) {
      setManualError("Please enter customer name.");
      return;
    }
    setManualLoading(true);
    try {
      await bookToken({
        uid: "walk-in-" + Date.now(),
        customerName: manualName.trim(),
        phone: manualPhone.trim() || null,
        service: manualService,
      });
      setManualName("");
      setManualPhone("");
    } catch (err) {
      setManualError("Failed to add walk-in customer. Please try again.");
    }
    setManualLoading(false);
  }

  return (
    <div style={{ minHeight: "100vh", backgroundColor: "#0f172a", fontFamily: "'Inter', sans-serif", color: "#f8fafc", padding: "12px 10px" }}>
      <div style={{ maxWidth: "1100px", margin: "0 auto" }}>

        {/* Top Navbar Header */}
        <header style={{ display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: "12px 16px", backgroundColor: "#1e293b", borderRadius: "12px", marginBottom: "16px", border: "1px solid #334155", gap: "12px", flexWrap: "wrap" }}>
          <div style={{ fontSize: "20px", fontWeight: "800", letterSpacing: "-0.5px" }}>
            salon<span style={{ color: "#d4af37" }}>queue</span>
          </div>
          <div style={{ display: "flex", alignItems: "center", gap: "10px", fontSize: "13px" }}>
            <span style={{ color: "#94a3b8", maxWidth: "180px", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
              <strong style={{ color: "#f8fafc" }}>{user.displayName || user.email}</strong>
            </span>
            <button
              onClick={logout}
              style={{ background: "#ef444422", color: "#f87171", border: "1px solid #ef444444", padding: "6px 12px", borderRadius: "8px", cursor: "pointer", fontWeight: "600", fontSize: "12px" }}
            >
              Logout
            </button>
          </div>
        </header>

        {/* Analytics & Overview Dashboard Card */}
        <section style={{ backgroundColor: "#1e293b", borderRadius: "16px", padding: "16px", marginBottom: "16px", border: "1px solid #334155" }}>
          <div style={{ display: "flex", flexWrap: "wrap", justifyContent: "space-between", alignItems: "center", gap: "12px", marginBottom: "16px" }}>
            <div>
              <h2 style={{ fontSize: "18px", fontWeight: "700", margin: 0 }}>Today's Live Metrics</h2>
              <p style={{ margin: "2px 0 0 0", fontSize: "12px", color: "#94a3b8" }}>Real-time status of your salon</p>
            </div>
            <button
              onClick={exportToPDF}
              style={{ width: "100%", smWidth: "auto", backgroundColor: "#d4af37", color: "#0f172a", padding: "10px 14px", borderRadius: "8px", fontWeight: "700", border: "none", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: "6px", fontSize: "13px" }}
            >
              📄 Export PDF Report
            </button>
          </div>

          {/* Quick Metrics Grid */}
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(100px, 1fr))", gap: "10px", marginBottom: "16px" }}>
            <div style={{ backgroundColor: "#0f172a", padding: "12px", borderRadius: "10px", border: "1px solid #334155" }}>
              <span style={{ fontSize: "10px", color: "#94a3b8", textTransform: "uppercase", fontWeight: "600" }}>Total</span>
              <div style={{ fontSize: "22px", fontWeight: "800", marginTop: "2px" }}>{totalToday}</div>
            </div>
            <div style={{ backgroundColor: "#0f172a", padding: "12px", borderRadius: "10px", border: "1px solid #334155" }}>
              <span style={{ fontSize: "10px", color: "#22c55e", textTransform: "uppercase", fontWeight: "600" }}>Done</span>
              <div style={{ fontSize: "22px", fontWeight: "800", color: "#22c55e", marginTop: "2px" }}>{completedToday}</div>
            </div>
            <div style={{ backgroundColor: "#0f172a", padding: "12px", borderRadius: "10px", border: "1px solid #334155" }}>
              <span style={{ fontSize: "10px", color: "#f59e0b", textTransform: "uppercase", fontWeight: "600" }}>In Queue</span>
              <div style={{ fontSize: "22px", fontWeight: "800", color: "#f59e0b", marginTop: "2px" }}>{remainingToday}</div>
            </div>
          </div>

          {/* Service Statistics Badges */}
          <div style={{ fontSize: "12px", color: "#cbd5e1", borderTop: "1px solid #334155", paddingTop: "12px", display: "flex", alignItems: "center", gap: "8px", flexWrap: "wrap" }}>
            <strong style={{ color: "#94a3b8", width: "100%" }}>Service Breakdown:</strong>
            {serviceStats.map((s) => (
              <span key={s.service} style={{ background: "#0f172a", padding: "4px 8px", borderRadius: "6px", border: "1px solid #334155", fontSize: "11px" }}>
                {s.service}: <strong style={{ color: "#d4af37" }}>{s.count}</strong>
              </span>
            ))}
          </div>
        </section>

        {/* Walk-in Customer Form */}
        <section style={{ backgroundColor: "#1e293b", padding: "16px", borderRadius: "16px", marginBottom: "16px", border: "1px solid #334155" }}>
          <h3 style={{ fontSize: "15px", fontWeight: "700", marginBottom: "12px", color: "#f8fafc" }}>➕ Add Walk-in Customer</h3>
          <form onSubmit={handleManualBooking} style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
            <input
              type="text"
              placeholder="Customer Name *"
              value={manualName}
              onChange={(e) => setManualName(e.target.value)}
              style={{ width: "100%", padding: "12px", borderRadius: "8px", backgroundColor: "#0f172a", border: "1px solid #334155", color: "#fff", outline: "none", fontSize: "14px" }}
              required
            />
            <input
              type="text"
              placeholder="Phone Number (Optional)"
              value={manualPhone}
              onChange={(e) => setManualPhone(e.target.value)}
              style={{ width: "100%", padding: "12px", borderRadius: "8px", backgroundColor: "#0f172a", border: "1px solid #334155", color: "#fff", outline: "none", fontSize: "14px" }}
            />
            <select
              value={manualService}
              onChange={(e) => setManualService(e.target.value)}
              style={{ width: "100%", padding: "12px", borderRadius: "8px", backgroundColor: "#0f172a", border: "1px solid #334155", color: "#fff", outline: "none", fontSize: "14px" }}
            >
              {SERVICES.map((s) => (
                <option key={s.name} value={s.name}>
                  {s.name} ({s.duration} mins)
                </option>
              ))}
            </select>
            <button
              type="submit"
              disabled={manualLoading}
              style={{ width: "100%", padding: "12px", backgroundColor: "#3b82f6", color: "#fff", border: "none", borderRadius: "8px", fontWeight: "700", cursor: "pointer", fontSize: "14px" }}
            >
              {manualLoading ? "Adding..." : "+ Add to Queue"}
            </button>
          </form>
          {manualError && <div style={{ marginTop: "8px", color: "#ef4444", fontSize: "12px" }}>{manualError}</div>}
        </section>

        {/* Serving Now Spotlight Box */}
        {serving ? (
          <section
            style={{
              background: "linear-gradient(135deg, #1e293b 0%, #0f172a 100%)",
              padding: "20px 16px",
              borderRadius: "16px",
              border: "2px solid #d4af37",
              boxShadow: "0 8px 20px rgba(0,0,0,0.4)",
              marginBottom: "20px",
              textAlign: "center",
              position: "relative",
            }}
          >
            <span style={{ position: "absolute", top: "12px", right: "12px", background: "#22c55e", color: "#fff", padding: "3px 8px", borderRadius: "12px", fontSize: "10px", fontWeight: "800", letterSpacing: "0.5px" }}>
              NOW SERVING
            </span>

            <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: "10px", marginBottom: "12px", marginTop: "12px" }}>
              {renderAvatar(serving.customerName, serving.photoURL, 56)}
              <div>
                <h3 style={{ fontSize: "20px", fontWeight: "800", margin: 0 }}>{serving.customerName}</h3>
                <p style={{ margin: "2px 0 0 0", color: "#d4af37", fontSize: "13px", fontWeight: "600" }}>{serving.service}</p>
                {serving.phone && <span style={{ fontSize: "12px", color: "#94a3b8" }}>📞 {serving.phone}</span>}
              </div>
            </div>

            <div style={{ margin: "12px 0" }}>
              <div style={{ fontSize: "10px", color: "#94a3b8", letterSpacing: "1.5px", textTransform: "uppercase", fontWeight: "700" }}>Token Number</div>
              <div style={{ fontSize: "48px", fontWeight: "900", color: "#f59e0b", lineHeight: "1" }}>#{serving.tokenNumber}</div>
            </div>

            <div style={{ display: "flex", flexDirection: "column", gap: "8px", marginTop: "16px" }}>
              <button
                onClick={() => handleDone(serving)}
                disabled={busyId === serving.id}
                style={{ width: "100%", padding: "12px", backgroundColor: "#22c55e", color: "#fff", border: "none", borderRadius: "8px", fontWeight: "700", fontSize: "14px", cursor: "pointer" }}
              >
                ✓ Mark Completed
              </button>
              <button
                onClick={() => handleSkip(serving)}
                disabled={busyId === serving.id}
                style={{ width: "100%", padding: "10px", backgroundColor: "#f97316", color: "#fff", border: "none", borderRadius: "8px", fontWeight: "600", fontSize: "13px", cursor: "pointer" }}
              >
                Skip Token
              </button>
            </div>
          </section>
        ) : (
          <section style={{ backgroundColor: "#1e293b", padding: "16px", borderRadius: "16px", border: "1px solid #334155", marginBottom: "20px", display: "flex", flexDirection: "column", gap: "12px" }}>
            <div>
              {waiting.length > 0 ? (
                <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
                  {renderAvatar(waiting[0].customerName, waiting[0].photoURL, 40)}
                  <div>
                    <div style={{ fontWeight: "700", fontSize: "15px" }}>Next Up: #{waiting[0].tokenNumber}</div>
                    <div style={{ fontSize: "12px", color: "#94a3b8" }}>
                      {waiting[0].customerName} • <span style={{ color: "#d4af37" }}>{waiting[0].service}</span>
                    </div>
                  </div>
                </div>
              ) : (
                <span style={{ color: "#94a3b8", fontSize: "14px", textAlign: "center", display: "block" }}>No active customers waiting in queue.</span>
              )}
            </div>
            {waiting.length > 0 && (
              <button
                onClick={handleServeNext}
                style={{ width: "100%", padding: "12px", backgroundColor: "#d4af37", color: "#0f172a", border: "none", borderRadius: "8px", fontWeight: "800", cursor: "pointer", fontSize: "14px" }}
              >
                Start Serving Next ▶
              </button>
            )}
          </section>
        )}

        {/* Skipped Tokens Section */}
        {skippedTokens.length > 0 && (
          <section style={{ marginBottom: "20px" }}>
            <h3 style={{ fontSize: "14px", fontWeight: "700", color: "#f97316", marginBottom: "10px", textTransform: "uppercase", letterSpacing: "0.5px" }}>
              ⚠️ Skipped Tokens ({skippedTokens.length})
            </h3>
            <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
              {skippedTokens.map((t) => (
                <div key={t.id} style={{ display: "flex", flexDirection: "column", gap: "10px", padding: "12px", backgroundColor: "#1e293b", borderRadius: "12px", border: "1px solid #334155" }}>
                  <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
                    {renderAvatar(t.customerName, t.photoURL, 36)}
                    <div>
                      <div style={{ fontWeight: "700", fontSize: "14px" }}>#{t.tokenNumber} - {t.customerName}</div>
                      <div style={{ fontSize: "12px", color: "#94a3b8" }}>{t.service}</div>
                    </div>
                  </div>
                  <div style={{ display: "flex", gap: "8px", width: "100%" }}>
                    <button onClick={() => handleReinsert(t)} disabled={busyId === t.id} style={{ flex: 1, padding: "8px", backgroundColor: "#334155", color: "#fff", border: "none", borderRadius: "6px", cursor: "pointer", fontSize: "12px", fontWeight: "600" }}>
                      Re-insert
                    </button>
                    <button onClick={() => handleCancel(t)} disabled={busyId === t.id} style={{ flex: 1, padding: "8px", backgroundColor: "#ef444422", color: "#f87171", border: "1px solid #ef444444", borderRadius: "6px", cursor: "pointer", fontSize: "12px", fontWeight: "600" }}>
                      Cancel
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Main Waiting Queue List */}
        <section>
          <div style={{ display: "flex", flexDirection: "column", gap: "10px", marginBottom: "12px" }}>
            <h3 style={{ fontSize: "16px", fontWeight: "700", margin: 0 }}>Waiting Queue ({waiting.length})</h3>
            {waiting.length > 0 && (
              <input
                type="text"
                placeholder="Search name or token..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                style={{ width: "100%", padding: "10px", borderRadius: "8px", backgroundColor: "#1e293b", border: "1px solid #334155", color: "#fff", fontSize: "13px", outline: "none" }}
              />
            )}
          </div>

          <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
            {filteredWaiting.length === 0 && (
              <div style={{ padding: "20px", textAlign: "center", color: "#94a3b8", backgroundColor: "#1e293b", borderRadius: "12px", border: "1px solid #334155", fontSize: "13px" }}>
                {searchTerm ? "No matching customers found." : "No customers currently waiting in the queue."}
              </div>
            )}
            {filteredWaiting.map((t, i) => (
              <div key={t.id} style={{ display: "flex", flexDirection: "column", gap: "10px", padding: "12px", backgroundColor: "#1e293b", borderRadius: "12px", border: "1px solid #334155" }}>
                <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
                  {renderAvatar(t.customerName, t.photoURL, 38)}
                  <div style={{ flex: 1 }}>
                    <div style={{ fontWeight: "700", fontSize: "14px" }}>
                      #{t.tokenNumber} · {t.customerName}
                    </div>
                    <div style={{ fontSize: "11px", color: "#94a3b8", marginTop: "2px" }}>
                      <span style={{ color: "#d4af37" }}>{t.service}</span> • Est: ~{calculateWaitTime(i)} mins
                    </div>
                  </div>
                </div>

                <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", borderTop: "1px solid #334155", paddingTop: "8px" }}>
                  <span style={{ padding: "3px 8px", backgroundColor: "#0f172a", border: "1px solid #334155", borderRadius: "6px", fontSize: "11px", color: "#cbd5e1", fontWeight: "600" }}>
                    {i === 0 ? "Next Up" : `Position ${i + 1}`}
                  </span>
                  <button
                    onClick={() => handleCancel(t)}
                    disabled={busyId === t.id}
                    style={{ padding: "6px 12px", backgroundColor: "#ef444422", color: "#f87171", border: "1px solid #ef444444", borderRadius: "6px", cursor: "pointer", fontSize: "12px", fontWeight: "600" }}
                  >
                    Cancel
                  </button>
                </div>
              </div>
            ))}
          </div>
        </section>

      </div>
    </div>
  );
}