"use client";

import { useEffect, useState, useRef } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "../../lib/AuthContext";
import { listenQueueToday, setStatus, skipAndReinsert, bookToken } from "../../lib/queue";
import { db } from "../../lib/firebase";
import { doc, getDoc } from "firebase/firestore";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const SERVICES = [
  { name: "Hair Cut" },
  { name: "Shave" },
  { name: "Hair Colour" },
  { name: "Facial" },
  { name: "Hair Wash" },
];

export default function AdminPage() {
  const { user, role, loading } = useAuth();
  const router = useRouter();
  const [queue, setQueue] = useState([]);
  const [busyId, setBusyId] = useState(null);
  const [searchTerm, setSearchTerm] = useState("");
  const [adminPhotoURL, setAdminPhotoURL] = useState("");

  const [manualName, setManualName] = useState("");
  const [manualPhone, setManualPhone] = useState("");
  const [manualService, setManualService] = useState(SERVICES[0].name);
  const [manualLoading, setManualLoading] = useState(false);
  const [manualError, setManualError] = useState("");

  const prevQueueLength = useRef(0);

  useEffect(() => {
    if (loading) return;
    if (!user || (role !== "admin" && role !== "super-admin")) {
      router.replace("/login");
    }
  }, [user, role, loading, router]);

  useEffect(() => {
    async function loadAdminData() {
      if (!user) return;
      try {
        const userDoc = await getDoc(doc(db, "users", user.uid));
        if (userDoc.exists() && userDoc.data().photoURL) {
          setAdminPhotoURL(userDoc.data().photoURL);
        }
      } catch (e) {
        console.error("Error loading admin profile:", e);
      }
    }
    loadAdminData();
  }, [user]);

  useEffect(() => {
    const unsub = listenQueueToday((data) => {
      if (data.length > prevQueueLength.current && prevQueueLength.current !== 0) {
        playNotificationSound();
      }
      prevQueueLength.current = data.length;
      setQueue(data);
    });
    return () => unsub();
  }, []);

  const playNotificationSound = () => {
    try {
      const audio = new Audio("/sounds/notification.mp3");
      audio.play().catch(() => {});
    } catch (e) {
      console.log("Audio play error", e);
    }
  };

  const exportToPDF = () => {
    if (!queue.length) return;

    const doc = new jsPDF();
    const todayStr = new Date().toLocaleDateString();

    doc.setFontSize(18);
    doc.setTextColor(184, 134, 59);
    doc.text("Salon Queue Management - Daily Report", 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Date: ${todayStr}`, 14, 27);
    doc.text(`Generated By: ${user?.displayName || user?.email || "Admin"}`, 14, 32);

    const doneCount = queue.filter((t) => t.status === "done").length;
    const waitingCount = queue.filter((t) => t.status === "waiting").length;
    const servingCount = queue.filter((t) => t.status === "serving").length;

    doc.setFontSize(11);
    doc.setTextColor(40);
    doc.text(`Total Bookings: ${queue.length} | Completed: ${doneCount} | Waiting: ${waitingCount} | Serving: ${servingCount}`, 14, 42);

    const tableRows = queue.map((t) => [
      `#${t.tokenNumber}`,
      t.customerName,
      t.phone || "N/A",
      t.service,
      t.status === "done" ? "COMPLETED" : t.status.toUpperCase(),
    ]);

    autoTable(doc, {
      startY: 48,
      head: [["Token #", "Customer Name", "Phone", "Service", "Status"]],
      headStyles: { fillColor: [31, 58, 46], textColor: [241, 233, 216] },
      alternateRowStyles: { fillColor: [241, 233, 216] },
      styles: { fontSize: 9, cellPadding: 3 },
    });

    doc.save(`salon_queue_report_${new Date().toISOString().slice(0, 10)}.pdf`);
  };

  if (loading || !user) {
    return (
      <div className="shell">
        <p style={{ color: "#6c6459", padding: 20 }}>Loading...</p>
      </div>
    );
  }

  const waiting = queue.filter((t) => t.status === "waiting");
  const serving = queue.find((t) => t.status === "serving");
  const skippedTokens = queue.filter((t) => t.status === "skipped");
  const doneTokens = queue.filter((t) => t.status === "done");

  const totalToday = queue.length;
  const completedToday = doneTokens.length;
  const remainingToday = waiting.length + (serving ? 1 : 0);

  const activeQueue = serving ? [serving, ...waiting] : waiting;

  const filteredActiveQueue = activeQueue.filter(
    (t) =>
      t.customerName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      t.tokenNumber.toString().includes(searchTerm)
  );

  const serviceStats = SERVICES.map((svc) => {
    const count = queue.filter((t) => t.service === svc.name).length;
    return { service: svc.name, count };
  });

  const renderAvatar = (name, photoURL, size = 40) => {
    if (photoURL) {
      return (
        <img
          src={photoURL}
          alt={name || "Customer"}
          style={{ width: size, height: size, borderRadius: "50%", objectFit: "cover", border: "2px solid #b8863b", flexShrink: 0 }}
        />
      );
    }
    const initial = name ? name.charAt(0).toUpperCase() : "?";
    return (
      <div
        style={{
          width: size,
          height: size,
          borderRadius: "50%",
          backgroundColor: "#cbd5e1",
          color: "#475569",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          fontWeight: "bold",
          fontSize: size * 0.4,
          flexShrink: 0,
        }}
      >
        {initial}
      </div>
    );
  };

  async function handleServeNext() {
    const next = waiting[0];
    if (!next) return;
    setBusyId(next.id);
    await setStatus(next.id, "serving");
    setBusyId(null);
  }

  async function handleDone(token) {
    setBusyId(token.id);
    await setStatus(token.id, "done");
    setBusyId(null);
  }

  async function handleSkip(token) {
    setBusyId(token.id);
    await setStatus(token.id, "skipped");
    setBusyId(null);
  }

  async function handleCancel(token) {
    if (confirm(`Are you sure you want to cancel token #${token.tokenNumber}?`)) {
      setBusyId(token.id);
      await setStatus(token.id, "cancelled");
      setBusyId(null);
    }
  }

  async function handleReinsert(token) {
    setBusyId(token.id);
    const currentOrdered = queue.filter((t) => t.status === "waiting" || t.status === "serving");
    await skipAndReinsert(token.id, currentOrdered.length ? currentOrdered : queue);
    setBusyId(null);
  }

  async function handleManualBooking(e) {
    e.preventDefault();
    setManualError("");
    if (!manualName.trim()) {
      setManualError("Please enter customer name.");
      return;
    }
    setManualLoading(true);
    try {
      await bookToken({
        uid: "walk-in-" + Date.now(),
        customerName: manualName.trim(),
        phone: manualPhone.trim() || null,
        service: manualService,
      });
      setManualName("");
      setManualPhone("");
    } catch (err) {
      setManualError("Failed to add walk-in customer. Please try again.");
    }
    setManualLoading(false);
  }

  return (
    <div className="shell" style={{ minHeight: "100vh", backgroundColor: "#eee7d8", fontFamily: "'Inter', sans-serif" }}>
      
      {/* Topbar Header matching Customer page format with Avatar */}
      <div className="topbar" style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <div className="brand" style={{ marginBottom: 0 }}>
          Salon<span>Yasi</span>
        </div>

        {/* Profile Avatar Button */}
        <div
          onClick={() => router.push("/admin/profile")}
          style={{ cursor: "pointer", display: "flex", alignItems: "center" }}
          title="Go to Admin Profile Settings"
        >
          {adminPhotoURL || user.photoURL ? (
            <img
              src={adminPhotoURL || user.photoURL}
              alt="Admin Profile"
              style={{
                width: 40,
                height: 40,
                borderRadius: "50%",
                objectFit: "cover",
                border: "2px solid #e4ddc7",
              }}
            />
          ) : (
            <div
              style={{
                width: 40,
                height: 40,
                borderRadius: "50%",
                background: "#4a5568",
                color: "#fff",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                fontWeight: "bold",
                fontSize: 16,
                border: "2px solid #e4ddc7",
              }}
            >
              {user.displayName ? user.displayName.charAt(0).toUpperCase() : "A"}
            </div>
          )}
        </div>
      </div>

      <div className="content" style={{ maxWidth: "960px", margin: "0 auto", padding: "24px 16px 60px" }}>

        {/* 1. Serving Now Spotlight Hero Box (Most Important) */}
        {serving ? (
          <section
            style={{
              backgroundColor: "#1f3a2e",
              padding: "24px 20px",
              borderRadius: "10px",
              border: "2px solid #b8863b",
              boxShadow: "0 8px 25px rgba(20, 39, 32, 0.4)",
              marginBottom: "24px",
              textAlign: "center",
              position: "relative",
              color: "#f1e9d8",
            }}
          >
            <span style={{ position: "absolute", top: "14px", right: "14px", backgroundColor: "#28a745", color: "#ffffff", padding: "5px 12px", borderRadius: "20px", fontSize: "11px", fontWeight: "800", letterSpacing: "0.5px", display: "inline-flex", alignItems: "center", gap: "6px", boxShadow: "0 0 10px rgba(40, 167, 69, 0.5)" }}>
              <span className="pulse-green-dot" style={{ backgroundColor: "#ffffff" }}></span> ✂️ CUTTING
            </span>

            <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: "10px", marginBottom: "14px", marginTop: "10px" }}>
              {renderAvatar(serving.customerName, serving.customerPhotoURL || serving.photoURL, 58)}
              <div>
                <h3 style={{ fontFamily: "'Fraunces', serif", fontSize: "22px", fontWeight: "700", margin: 0, color: "#f1e9d8" }}>{serving.customerName}</h3>
                <p style={{ margin: "4px 0 0 0", color: "#b8863b", fontSize: "14px", fontWeight: "600" }}>{serving.service}</p>
                {serving.phone && <span style={{ fontSize: "13px", color: "#b9c9bd" }}>📞 {serving.phone}</span>}
              </div>
            </div>

            <div style={{ margin: "14px 0" }}>
              <div style={{ fontSize: "11px", color: "#b9c9bd", letterSpacing: "1.5px", textTransform: "uppercase", fontWeight: "700" }}>Token Number</div>
              <div style={{ fontFamily: "'Fraunces', serif", fontSize: "56px", fontWeight: "800", color: "#b8863b", lineHeight: "1" }}>#{serving.tokenNumber}</div>
            </div>

            <div style={{ display: "flex", flexDirection: "column", gap: "10px", marginTop: "18px" }}>
              <button
                onClick={() => handleDone(serving)}
                disabled={busyId === serving.id}
                style={{ width: "100%", padding: "12px", backgroundColor: "#28a745", color: "#ffffff", border: "none", borderRadius: "4px", fontWeight: "700", fontSize: "14px", cursor: "pointer" }}
              >
                ✓ Mark Completed
              </button>
              <button
                onClick={() => handleSkip(serving)}
                disabled={busyId === serving.id}
                style={{ width: "100%", padding: "10px", backgroundColor: "#b8863b", color: "#241a09", border: "none", borderRadius: "4px", fontWeight: "700", fontSize: "13px", cursor: "pointer" }}
              >
                Skip Token
              </button>
            </div>
          </section>
        ) : (
          <section style={{ backgroundColor: "#f1e9d8", padding: "20px", borderRadius: "8px", border: "1px solid #dfd2b4", marginBottom: "24px", display: "flex", flexDirection: "column", gap: "14px" }}>
            <div>
              {waiting.length > 0 ? (
                <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
                  {renderAvatar(waiting[0].customerName, waiting[0].customerPhotoURL || waiting[0].photoURL, 44)}
                  <div>
                    <div style={{ fontWeight: "700", fontSize: "16px", color: "#142720" }}>Next Up: #{waiting[0].tokenNumber}</div>
                    <div style={{ fontSize: "13px", color: "#6c6459" }}>
                      {waiting[0].customerName} • <span style={{ color: "#96692a", fontWeight: "600" }}>{waiting[0].service}</span>
                    </div>
                  </div>
                </div>
              ) : (
                <span style={{ color: "#6c6459", fontSize: "14px", textAlign: "center", display: "block" }}>No active customers waiting in queue.</span>
              )}
            </div>
            {waiting.length > 0 && (
              <button
                onClick={handleServeNext}
                style={{ width: "100%", padding: "12px", backgroundColor: "#b8863b", color: "#241a09", border: "none", borderRadius: "4px", fontWeight: "800", cursor: "pointer", fontSize: "14px" }}
              >
                Start Serving Next ▶
              </button>
            )}
          </section>
        )}

        {/* 2. Add Walk-in Customer Form */}
        <section style={{ backgroundColor: "#f1e9d8", padding: "20px", borderRadius: "8px", marginBottom: "24px", border: "1px solid #dfd2b4", boxShadow: "0 4px 15px rgba(0,0,0,0.05)" }}>
          <h3 style={{ fontFamily: "'Fraunces', serif", fontSize: "18px", fontWeight: "600", marginBottom: "14px", color: "#142720", marginTop: 0 }}>➕ Add Walk-in Customer</h3>
          <form onSubmit={handleManualBooking} style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
            <input
              type="text"
              placeholder="Customer Name *"
              value={manualName}
              onChange={(e) => setManualName(e.target.value)}
              style={{ width: "100%", padding: "11px 14px", borderRadius: "4px", backgroundColor: "#ffffff", border: "1.5px solid #dfd2b4", color: "#211d16", outline: "none", fontSize: "14px" }}
              required
            />
            <input
              type="text"
              placeholder="Phone Number (Optional)"
              value={manualPhone}
              onChange={(e) => setManualPhone(e.target.value)}
              style={{ width: "100%", padding: "11px 14px", borderRadius: "4px", backgroundColor: "#ffffff", border: "1.5px solid #dfd2b4", color: "#211d16", outline: "none", fontSize: "14px" }}
            />
            <select
              value={manualService}
              onChange={(e) => setManualService(e.target.value)}
              style={{ width: "100%", padding: "11px 14px", borderRadius: "4px", backgroundColor: "#ffffff", border: "1.5px solid #dfd2b4", color: "#211d16", outline: "none", fontSize: "14px" }}
            >
              {SERVICES.map((s) => (
                <option key={s.name} value={s.name}>
                  {s.name}
                </option>
              ))}
            </select>
            <button
              type="submit"
              disabled={manualLoading}
              style={{ width: "100%", padding: "12px", backgroundColor: "#1f3a2e", color: "#f1e9d8", border: "none", borderRadius: "4px", fontWeight: "700", cursor: "pointer", fontSize: "14px" }}
            >
              {manualLoading ? "Adding..." : "+ Add to Queue"}
            </button>
          </form>
          {manualError && <div style={{ marginTop: "10px", color: "#7a2b1e", backgroundColor: "#fbe3de", padding: "8px 12px", borderRadius: "4px", fontSize: "13px" }}>{manualError}</div>}
        </section>

        {/* 3. Skipped Tokens Section */}
        {skippedTokens.length > 0 && (
          <section style={{ marginBottom: "24px" }}>
            <h3 style={{ fontFamily: "'Fraunces', serif", fontSize: "16px", fontWeight: "700", color: "#9c4a3b", marginBottom: "12px", textTransform: "uppercase", letterSpacing: "0.5px" }}>
              ⚠️ Skipped Tokens ({skippedTokens.length})
            </h3>
            <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
              {skippedTokens.map((t) => (
                <div key={t.id} style={{ display: "flex", flexDirection: "column", gap: "10px", padding: "14px", backgroundColor: "#f1e9d8", borderRadius: "8px", border: "1px solid #dfd2b4" }}>
                  <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
                    {renderAvatar(t.customerName, t.customerPhotoURL || t.photoURL, 38)}
                    <div>
                      <div style={{ fontWeight: "700", fontSize: "15px", color: "#142720" }}>#{t.tokenNumber} - {t.customerName}</div>
                      <div style={{ fontSize: "13px", color: "#6c6459" }}>{t.service}</div>
                    </div>
                  </div>
                  <div style={{ display: "flex", gap: "10px", width: "100%" }}>
                    <button onClick={() => handleReinsert(t)} disabled={busyId === t.id} style={{ flex: 1, padding: "9px", backgroundColor: "#1f3a2e", color: "#f1e9d8", border: "none", borderRadius: "4px", cursor: "pointer", fontSize: "13px", fontWeight: "600" }}>
                      Re-insert
                    </button>
                    <button onClick={() => handleCancel(t)} disabled={busyId === t.id} style={{ flex: 1, padding: "9px", backgroundColor: "#d9534f", color: "#ffffff", border: "none", borderRadius: "4px", cursor: "pointer", fontSize: "13px", fontWeight: "600" }}>
                      Cancel
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* 4. Main Active Queue List (Matches Customer Page list format) */}
        <section style={{ marginBottom: "24px" }}>
          <div style={{ display: "flex", flexDirection: "column", gap: "12px", marginBottom: "14px" }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
              <h3 className="section-title" style={{ margin: 0 }}>
                Queue List ({activeQueue.length})
              </h3>
              {serving && (
                <span style={{ fontSize: "13px", color: "#28a745", fontWeight: "700", display: "inline-flex", alignItems: "center", gap: "6px" }}>
                  <span className="pulse-green-dot"></span> 1 Cutting Now
                </span>
              )}
            </div>
            {activeQueue.length > 0 && (
              <input
                type="text"
                placeholder="Search name or token..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                style={{ width: "100%", padding: "11px 14px", borderRadius: "4px", backgroundColor: "#ffffff", border: "1.5px solid #dfd2b4", color: "#211d16", fontSize: "14px", outline: "none" }}
              />
            )}
          </div>

          <div className="queue-list" style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
            {filteredActiveQueue.length === 0 && (
              <div className="empty-note" style={{ textAlign: "center", padding: "20px" }}>
                {searchTerm ? "No matching customers found." : "No customers currently in the queue."}
              </div>
            )}
            {filteredActiveQueue.map((t) => {
              const isServing = t.status === "serving";

              return (
                <div
                  key={t.id}
                  className="queue-row"
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: 12,
                    padding: "12px 16px",
                    backgroundColor: isServing ? "rgba(40, 167, 69, 0.12)" : "#f1e9d8",
                    borderRadius: "6px",
                    border: isServing ? "2px solid #28a745" : "1px solid #dfd2b4",
                    boxShadow: isServing ? "0 4px 15px rgba(40, 167, 69, 0.25)" : "none",
                  }}
                >
                  {/* Customer Avatar */}
                  {renderAvatar(t.customerName, t.customerPhotoURL || t.photoURL, 40)}

                  {/* Token Number */}
                  <div className="n">#{t.tokenNumber}</div>

                  {/* Customer Info */}
                  <div className="info" style={{ flex: 1 }}>
                    <div className="svc">{t.service}</div>
                    <div className="meta">
                      {t.customerName} {t.phone ? `(${t.phone})` : ""}
                    </div>
                  </div>

                  {/* Status & Actions */}
                  {isServing ? (
                    <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                      <span
                        style={{
                          backgroundColor: "#28a745",
                          color: "#ffffff",
                          padding: "4px 0",
                          minWidth: "90px",
                          textAlign: "center",
                          display: "inline-block",
                          borderRadius: "4px",
                          fontSize: "12px",
                          fontWeight: "bold",
                        }}
                      >
                        Cutting
                      </span>
                      <button
                        onClick={() => handleDone(t)}
                        disabled={busyId === t.id}
                        style={{
                          padding: "6px 12px",
                          backgroundColor: "#28a745",
                          color: "#fff",
                          border: "none",
                          borderRadius: "4px",
                          cursor: "pointer",
                          fontSize: "12px",
                          fontWeight: "700",
                        }}
                      >
                        ✓ Done
                      </button>
                      <button
                        onClick={() => handleSkip(t)}
                        disabled={busyId === t.id}
                        style={{
                          padding: "6px 12px",
                          backgroundColor: "#b8863b",
                          color: "#241a09",
                          border: "none",
                          borderRadius: "4px",
                          cursor: "pointer",
                          fontSize: "12px",
                          fontWeight: "700",
                        }}
                      >
                        Skip
                      </button>
                    </div>
                  ) : (
                    <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                      <span
                        className="tag waiting"
                        style={{
                          minWidth: "90px",
                          textAlign: "center",
                          display: "inline-block",
                          padding: "4px 0",
                          borderRadius: "4px",
                          backgroundColor: "#e4dcc4",
                          color: "#5c5138",
                          fontSize: "12px",
                          fontWeight: "bold",
                        }}
                      >
                        Waiting
                      </span>
                      <button
                        onClick={() => handleCancel(t)}
                        disabled={busyId === t.id}
                        style={{
                          padding: "6px 12px",
                          backgroundColor: "#d9534f",
                          color: "#ffffff",
                          border: "none",
                          borderRadius: "4px",
                          cursor: "pointer",
                          fontSize: "12px",
                          fontWeight: "600",
                        }}
                      >
                        Cancel
                      </button>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </section>

        {/* 5. Today's Live Metrics & Service Breakdown (Placed Last / Anthimatama) */}
        <section style={{ backgroundColor: "#f1e9d8", borderRadius: "8px", padding: "20px", border: "1px solid #dfd2b4", boxShadow: "0 4px 15px rgba(0,0,0,0.05)" }}>
          <div style={{ display: "flex", flexWrap: "wrap", justifyContent: "space-between", alignItems: "center", gap: "12px", marginBottom: "16px" }}>
            <div>
              <h2 style={{ fontFamily: "'Fraunces', serif", fontSize: "18px", fontWeight: "600", color: "#142720", margin: 0 }}>Today's Live Metrics</h2>
              <p style={{ margin: "2px 0 0 0", fontSize: "13px", color: "#6c6459" }}>Daily statistics summary</p>
            </div>
            <button
              onClick={exportToPDF}
              style={{ backgroundColor: "#b8863b", color: "#241a09", padding: "9px 14px", borderRadius: "4px", fontWeight: "700", border: "none", cursor: "pointer", display: "flex", alignItems: "center", gap: "6px", fontSize: "13px" }}
            >
              📄 Export PDF Report
            </button>
          </div>

          {/* Quick Metrics Grid */}
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(110px, 1fr))", gap: "12px", marginBottom: "16px" }}>
            <div style={{ backgroundColor: "#e5dccb", padding: "14px", borderRadius: "6px", border: "1px solid #dfd2b4" }}>
              <span style={{ fontSize: "11px", color: "#6c6459", textTransform: "uppercase", fontWeight: "700" }}>Total</span>
              <div style={{ fontSize: "24px", fontWeight: "800", color: "#142720", marginTop: "2px" }}>{totalToday}</div>
            </div>
            <div style={{ backgroundColor: "#dcecdf", padding: "14px", borderRadius: "6px", border: "1px solid #b6d6bc" }}>
              <span style={{ fontSize: "11px", color: "#1f3a2e", textTransform: "uppercase", fontWeight: "700" }}>Done</span>
              <div style={{ fontSize: "24px", fontWeight: "800", color: "#28a745", marginTop: "2px" }}>{completedToday}</div>
            </div>
            <div style={{ backgroundColor: "#f7ecdc", padding: "14px", borderRadius: "6px", border: "1px solid #e6ceb0" }}>
              <span style={{ fontSize: "11px", color: "#96692a", textTransform: "uppercase", fontWeight: "700" }}>In Queue</span>
              <div style={{ fontSize: "24px", fontWeight: "800", color: "#b8863b", marginTop: "2px" }}>{remainingToday}</div>
            </div>
          </div>

          {/* Service Statistics Badges */}
          <div style={{ fontSize: "12px", color: "#211d16", borderTop: "1px solid #dfd2b4", paddingTop: "12px", display: "flex", alignItems: "center", gap: "8px", flexWrap: "wrap" }}>
            <strong style={{ color: "#6c6459", width: "100%" }}>Service Breakdown:</strong>
            {serviceStats.map((s) => (
              <span key={s.service} style={{ backgroundColor: "#e5dccb", padding: "4px 10px", borderRadius: "4px", border: "1px solid #dfd2b4", fontSize: "12px", color: "#142720" }}>
                {s.service}: <strong style={{ color: "#96692a" }}>{s.count}</strong>
              </span>
            ))}
          </div>
        </section>

      </div>
    </div>
  );
}